-name: Install nginx and run the service
hosts: localhost
become: yes
tasks: 
-name: install nginx
ansible.builtin.package:
  name: nginx
  state: present

-name: run the nginx service
ansible.builtin.service:
  name: nginx 
  state: restarted


