- name: PLAY LEVEL VARIABLES
  hosts: localhost
  become: yes
  vars:
    COURSE: "DEVOPS"
    TRAINER: "SivaKumar"
    DURATION: "110HRS"
  tasks:
  -name: CHECK VARIABLES
   ansible.builtin.command:
    msg: "Hi i am learning {{COURSE}} Trainer is {{TRAINER:}} Duration is {{DURATION:}}"
