- name: Datatypes
  hosts: localhost
  vars:
    Name: Narasimha ## Key Value Pair 
    Skills:  ## List data type
      - Devops
      - AWS
      - Ansible
      - Linux
    Experience:  ## Map data type
      - Devops: 1
      - AWS: 4
      - Ansible: 1
    Trainer: true ## boolean data type

  tasks:
  - name: Print the values of Key values
    ansible.builtin.debug:
      msg: "Name is {{Name}}"

  - name: Print the values of List Data Types
    ansible.builtin.debug:
      msg: "Skills are {{Skills}}"

  - name: Print the values of Map Data Types
    ansible.builtin.debug:
      msg: "Experience is {{Experience}}"

  - name: Print the values of boolean Data Types
    ansible.builtin.debug:
      msg: "Narasimha is your trainer siva: {{Trainer}}"

